CREATE TABLE habits_catalog (
	habit_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(256) NOT NULL UNIQUE,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	active BOOLEAN DEFAULT TRUE
)
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_unicode_ci;
